### PR TITLE
add link to witness profile

### PR DESCRIPTION
**Pull request by gidsg**
CC @guardian/discussion @Jholder112233 
screen shot 2015-10-16 at 10 50 53

### CODE REVIEW

**Comment by holder-josh** [comment]
:+1:

**Comment by chriswilk** [comment]
@Jholder112233 - can we deploy this on Monday please?

**Comment by holder-josh** [comment]
@chriswilk Everyone likes a Friday evening deploy - just shipped this and it seems to be working fine!

**Comment by chriswilk** [comment]
LOVELY!

Chris Wilk

Product Manager, Platforms

Guardian News & Media

---

chris.wilk@theguardian.com

---

@chrisalexwilk https://twitter.com/chrisalexwilk
LinkedIn http:///

---

Kings Place, 90 York Way,

London N1 9GU

theguardian.com

​-----

​​Download the Guardian app for Android
https://play.google.com/store/apps/details?id=com.guardian&hl=en_GB and
iOS​ https://itunes.apple.com/gb/app/the-guardian/id409128287?mt=8

​-----

On 16 October 2015 at 17:20, Josh Holder notifications@github.com wrote:

> @chriswilk https://github.com/chriswilk Everyone likes a Friday evening
> deploy - just shipped this and it seems to be working fine!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/guardian/interactive-witness-template/pull/3#issuecomment-148759046
> .

## 

---

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.

Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Pull request merged**
